version = 1

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "21"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "vue",
    "ember",
    "meteor",
    "angular",
    "angularjs"
  ]
  environment = [
    "nodejs",
    "browser",
    "jest",
    "mocha",
    "jasmine",
    "jquery",
    "mongo",
    "cypress",
    "vitest"
  ]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[code_formatters]]
name = "prettier"

[[code_formatters]]
name = "standardjs"

[[code_formatters]]
name = "isort"

[[code_formatters]]
name = "black"

[[code_formatters]]
name = "yapf"

[[code_formatters]]
name = "ruff"

[[code_formatters]]
name = "autopep8"